export const STEPS = {
  LANGUAGE_SELECTION: "LANGUAGE_SELECTION",
  TIMING_OVERVIEW: "TIMING_OVERVIEW",
  TIME_SELECTION: "TIME_SELECTION",
  WEEKDAY_SELECTION: "WEEKDAY_SELECTION",
  SETUP_FINISH: "SETUP_FINISH",
};
